package models

import "time"

// CrunchyrollImportEnvelope represents the top-level root JSON structure
// generated by CrunchyExporter backup files.
type CrunchyrollImportEnvelope struct {
	LastSync string          `json:"last_sync"`
	Episodes []IngestPayload `json:"episodes"` // Plucks the array out seamlessly
}

// IngestPayload mirrors high-volume tracking data arriving at the API gateway.
// This structure handles both bulk history migration files and real-time delta tracking.
type IngestPayload struct {
	Username      string    `json:"username"`  // Bound at the API gateway level via URL params
	Sentiment     int       `json:"sentiment"` // Bound at the API gateway level [-1, 0, 1]
	SeriesID      string    `json:"series_id"`
	SeriesTitle   string    `json:"series_title"`
	SeasonNumber  int       `json:"season_number"`
	EpisodeNumber float64   `json:"episode_number"`
	EpisodeTitle  string    `json:"episode_title"`
	EpisodeID     string    `json:"episode_id"`
	WatchedAt     time.Time `json:"watched_at"`
	FullyWatched  bool      `json:"fully_watched"`
}

// User represents a local account identity mapping directly to the relational database users table.
type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

// MediaCatalog represents the local autonomous cache layer for third-party metadata.
type MediaCatalog struct {
	ID                 int64     `json:"id"`
	ExternalID         string    `json:"external_id"`
	TitleRomaji        string    `json:"title_romaji"`
	TitleEnglish       string    `json:"title_english,omitempty"`
	Format             string    `json:"format"`
	Status             string    `json:"status"`
	TotalEpisodesCount int       `json:"total_episodes_count"`
	UpdatedAt          time.Time `json:"updated_at"`
}

// WatchProgress records isolated user sync checkpoints mapping to progress ledger tables.
type WatchProgress struct {
	UserID                 int64     `json:"user_id"`
	MediaID                int64     `json:"media_id"`
	CurrentEpisodeProgress float64   `json:"current_episode_progress"`
	LastWatchedAt          time.Time `json:"last_watched_at"`
	Sentiment              int       `json:"sentiment"`
}

// UserEngagement represents the computed consumption depth metrics for a specific title.
type UserEngagement struct {
	MediaID         int64
	BaseTitle       string
	EpisodesWatched int
	TotalEpisodes   int
	Score           float64
	IsTasteAnchor   bool
}
